language: python

python:
  - 3.7

cache: pip

install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: lint
      script:
        - isort --check-only --line-length 140 .
        - pycodestyle --config=.pycodestyle -- .
        - pylint --load-plugins pylint_quotes -- *.py
