version: '2'
services:
  db:
    image: mongo:4.4.3-bionic
    user: "{{user-settings}}"
    command: mongod --dbpath=/dbdata
    stop_signal: SIGINT
    ports:
     - "127.0.0.1:27017:27017"
    volumes:
      - ./dbdata:/dbdata:rw
      - ./dbdata:/data:rw

  initiate:
    image: mongo:4.4.3-bionic
    user: "{{user-settings}}"
    command: /bin/bash /userconfig/startup/mongors.sh /real_data/startup/mongo-initialized
    volumes:
      - ./dbdata:/dbdata:rw
      - ./dbdata:/data:rw
      - .:/userconfig:ro
      - ./data:/real_data
    depends_on:
      - db

  server:
    image: "{{docker-server-image}}"
    user: "{{user-settings}}"
    logging:
      driver: "json-file"
      options:
        max-size: "25M"
        max-file: "10"
    command: /bin/bash /userconfig/startup/wait.sh /data/startup/mongo-initialized /userconfig/startup/startServer.sh
    environment:
      - LD_LIBRARY_PATH=/usr/catapult/lib:/usr/catapult/deps
    stop_signal: SIGINT
    ports:
      - "7900:7900"
    volumes:
      - .:/userconfig:ro
      - ./nemesis/seed:/seed:ro
      - ./data:/data
      - ./logs:/logs
      - ./votingkeys:/votingkeys

  broker:
    image: "{{docker-server-image}}"
    user: "{{user-settings}}"
    cap_add:
     - SYS_PTRACE
    command: /bin/bash /userconfig/startup/wait.sh /data/startup/datadir-initialized /userconfig/startup/startBroker.sh
    environment:
      - LD_LIBRARY_PATH=/usr/catapult/lib:/usr/catapult/deps
    stop_signal: SIGINT
    volumes:
      - .:/userconfig:ro
      - ./data:/data
      - ./logs:/logs

  node:
    image: "{{docker-rest-image}}"
    user: "{{user-settings}}"
    command: /bin/ash /userconfig/startup/delaynode.sh
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    volumes:
      - .:/userconfig:ro
      - ./data:/data
